<?php

namespace Tkuska\TerytBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\AbstractQuery;

/**
 * MiejscowoscRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiejscowoscRepository extends EntityRepository
{
    /**
     * Funkcja pobiera jako parametr nazwę województwa bądź jej część i zwraca wszystki pasujące rekordy.
     *
     * @param string $name
     * @param string $wojewodztwo
     *
     * @return DoctrineCollection
     */
    public function getMiejscowoscByName($name, $wojewodztwo = null, $powiat = null, $gmina = null)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m.nazwa, m.woj, m.pow, m.gmi, m.rodz_gmi as rodzgmi, w.nazwa as wojewodztwo, p.nazwa as powiat, g.nazwa as gmina')
                ->distinct()
                ->from('TkuskaTerytBundle:Miejscowosc', 'm')
                ->leftJoin('m.wojewodztwo', 'w')
                ->leftJoin('m.powiat', 'p')
                ->leftJoin('m.gmina', 'g')
                ->where('m.nazwa like :nazwa');
        if ($wojewodztwo) {
            $qb->andWhere('m.woj = :wojewodztwo')
                    ->setParameter('wojewodztwo', $wojewodztwo);
        }
        if ($powiat) {
            $qb->andWhere('m.pow = :powiat')
                    ->setParameter('powiat', $powiat);
        }
        if ($gmina) {
            $qb->andWhere('m.gmi = :gmina')
                    ->setParameter('gmina', $gmina);
        }
        $qb->setParameter('nazwa', $name.'%')
                ->orderBy('m.nazwa');

        return $qb->getQuery()
                ->useQueryCache(true)
                ->useResultCache(true)
                ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     * Zapytanie dołączające miejscowosci do województw.
     *
     * @return \Doctrine\ORM\NativeQuery
     */
    public function dolaczMiejscowosciDoWojewodztw()
    {
        $rsm = new ResultSetMapping();
        $this->_em->createNativeQuery('UPDATE teryt_miejscowosci m 
            SET  wojewodztwo_id = ( 
            SELECT  id 
            FROM  teryt_wojewodztwa w
            WHERE w.WOJ = m.WOJ)', $rsm)
                ->getResult(AbstractQuery::HYDRATE_SCALAR);
    }

    /**
     * Zapytanie dołaczające miejscowości do powiatów.
     *
     * @return \Doctrine\ORM\NativeQuery
     */
    public function dolaczMiejscowosciDoPowiatow()
    {
        $rsm = new ResultSetMapping();
        $this->_em->createNativeQuery('UPDATE teryt_miejscowosci m 
            SET  powiat_id = ( 
            SELECT  id 
            FROM  teryt_powiaty p
            WHERE p.WOJ = m.WOJ AND p.POW = m.POW)', $rsm)
                ->getResult(AbstractQuery::HYDRATE_SCALAR);
    }

    /**
     * Zapytanie dołaczające miejscowości do gmin.
     *
     * @return \Doctrine\ORM\NativeQuery
     */
    public function dolaczMiejscowosciDoGmin()
    {
        $rsm = new ResultSetMapping();
        $this->_em->createNativeQuery('UPDATE teryt_miejscowosci m 
            SET  gmina_id = ( 
            SELECT  id 
            FROM  teryt_gminy p
            WHERE p.WOJ = m.WOJ AND p.POW = m.POW AND p.GMI = m.GMI AND p.RODZ = m.RODZ_GMI)', $rsm)
                ->getResult(AbstractQuery::HYDRATE_SCALAR);
    }
}
