<?php

namespace Tkuska\TerytBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\AbstractQuery;

/**
 * PowiatRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PowiatRepository extends EntityRepository
{
    /**
     * Funkcja pobiera jako parametr nazwę województwa bądź jej część i zwraca wszystki pasujące rekordy.
     *
     * @param string $name
     * @param string $wojewodztwo
     *
     * @return DoctrineCollection
     */
    public function getPowiatByName($name = '', $wojewodztwo = null)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p.nazwa, p.nazdod, p.woj, p.pow, w.nazwa as wojewodztwo')
                        ->from('TkuskaTerytBundle:Powiat', 'p')
                        ->leftJoin('p.wojewodztwo', 'w');

        if ($wojewodztwo) {
            $qb->andWhere('p.woj = :wojewodztwo')
                ->setParameter('wojewodztwo', $wojewodztwo);
        }
        $qb->where('p.nazwa like :nazwa')
            ->setParameter('nazwa', $name.'%')
            ->orderBy('p.nazwa');

        return $qb->getQuery()
                ->useQueryCache(true)
                ->useResultCache(true)
                ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     * Zapytanie dołączające powiaty do województw.
     *
     * @return \Doctrine\ORM\NativeQuery
     */
    public function dolaczPowiatyDoWojewodztw()
    {
        $rsm = new ResultSetMapping();
        $this->_em->createNativeQuery('UPDATE teryt_powiaty p 
            SET  wojewodztwo_id = ( 
            SELECT  id 
            FROM  teryt_wojewodztwa w
            WHERE w.WOJ = p.WOJ)', $rsm)
                ->getResult(AbstractQuery::HYDRATE_SCALAR);
    }
}
