<?php

namespace Tkuska\TerytBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\AbstractQuery;

/**
 * WojewodztwoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WojewodztwoRepository extends EntityRepository
{
    /**
     * Funkcja pobiera jako parametr nazwę województwa bądź jej część i zwraca wszystki pasujące rekordy.
     *
     * @param string $name
     *
     * @return DoctrineCollection
     */
    public function getWojewodztwoByName($name = '')
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('w.woj, w.nazwa, w.nazdod')
                ->from('TkuskaTerytBundle:Wojewodztwo', 'w')
                ->where('w.nazwa like :name')
                ->setParameter('name', $name.'%')
                                ->orderBy('w.nazwa');

        return $qb->getQuery()
                ->useQueryCache(true)
                ->useResultCache(true)
                ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
